# Generated by Django 5.1.3 on 2024-11-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lprs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewardtransactionview',
            fields=[
                ('transaction_id', models.AutoField(db_column='Transaction_ID', primary_key=True, serialize=False)),
                ('end', models.DateTimeField(blank=True, db_column='End', null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=500, null=True)),
                ('date', models.DateTimeField(db_column='Date')),
            ],
            options={
                'db_table': 'rewardtransactionview',
                'managed': False,
            },
        ),
    ]
