# Generated by Django 4.2.16 on 2024-11-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lprs', '0003_exclusiveproductrewardview_percentdiscountrewardview_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exclusiveproductrewardview',
        ),
        migrations.DeleteModel(
            name='Percentdiscountrewardview',
        ),
        migrations.DeleteModel(
            name='Pricediscountrewardview',
        ),
        migrations.DeleteModel(
            name='Productupgraderewardview',
        ),
        migrations.DeleteModel(
            name='Rewardtransactionview',
        ),
    ]
